---
title: Setup
---

```{r cp-release, include=FALSE}
# Get latest CellProfiler release
releases <- gh::gh("GET /repos/{owner}/{repo}/releases", 
               owner = "Cellprofiler",
               repo = "Cellprofiler")

pkg_version <- releases[[1]][["tag_name"]]
pkg_version <- substr(pkg_version,2,nchar(pkg_version))
```

### Setup
For this workshop, you will need to:

<a href="data/BBBC021_data.zip" download class="btn btn-primary" style="display:inline-block;padding:8px 12px;background:#007bff;color:#fff;border-radius:4px;text-decoration:none;">Download the dataset</a>

<a href="https://cellprofiler.org/releases" class="btn btn-primary" style="display:inline-block;padding:8px 12px;background:#007bff;color:#fff;border-radius:4px;text-decoration:none;">Download CellProfiler</a>

If you have any trouble with these steps, please let one of the teachers know
so they can help you set this up before proceeding. Once you are ready, navigate
to the exercise using the arrow buttons below.

::: callout
If you already have CellProfiler installed, please check whether it is the latest
version. You can do so in CellProfiler by clicking `Help > About CellProfiler`.
The latest version as of `r format(Sys.Date(), "%B %Y")` is `r pkg_version`. If you have version 4.2.0
or newer this workshop should work for you, though you may see a warning during
the reproducibility episode, which can be ignored. If you have an older version,
please install the latest version of CellProfiler before starting this workshop.
:::

### Help

If you get stuck at any step, first try to solve the issue yourself or with the
help of an instructor. If needed, you can also download a working version of the
pipeline here:

<a href="data/pipeline.cppipe" download class="btn btn-primary" style="display:inline-block;padding:8px 12px;background:#007bff;color:#fff;border-radius:4px;text-decoration:none;">Download pipeline</a>

:::::::::: callout
You may have to right click the button and select "Save Link As...".
::::::::::

After downloading the pipeline, you can compare it to yours for troubleshooting. 
To do so, first open a new CellProfiler window. 
Then, import this pipeline in CellProfiler by clicking on
`File` > `Import` > `Pipeline from File`.

### Further information
A lot of the information covered in this workshop are 
also covered in the [Ask Erin Dear Beth podcast](https://www.youtube.com/watch?v=JcfPQ44p3pc&list=PLCucasmZ3XNm24zV2bx-gG9InCAASqfOn)
series, a fantastic resource by Erin Weisbart and Beth Cimini.

CellProfiler also has a number of tutorials, like [this one](https://tutorials.cellprofiler.org/#beginner-segmentation)
on segmentation. And it also comes with extensive documentation, [found here](https://cellprofiler-manual.s3.amazonaws.com/CellProfiler-4.2.8/index.html).
